### Register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Pickle McSnort",
  "email": "pickle@example.com",
  "password": "123456"
}

### Log in an existing user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "pickle@example.com",
  "password": "123456"
}

### Get all users
GET http://localhost:3000/api/auth/all

### Get a user by ID
GET http://localhost:3000/api/auth/user/684b49e391442f3d7b7221d5

### Delete a user by ID
DELETE http://localhost:3000/api/auth/user/684b49e391442f3d7b7221d5



### PRODUCTION


### Register a new user
POST https://habit-tracker-api-eqos.onrender.com/api/auth/register
Content-Type: application/json

{
  "name": "Pickle McSnort",
  "email": "pickle@example.com",
  "password": "123456"
}

### Log in an existing user
POST https://habit-tracker-api-eqos.onrender.com/api/auth/login
Content-Type: application/json

{
  "email": "pickle@example.com",
  "password": "123456"
}

### Get all users
GET https://habit-tracker-api-eqos.onrender.com/api/auth/all

### Get a user by ID
GET https://habit-tracker-api-eqos.onrender.com/api/auth/user/68420378ecd9d47a2a9ae460

### Delete a user by ID
DELETE https://habit-tracker-api-eqos.onrender.com/api/auth/user/68420378ecd9d47a2a9ae460
