openapi: 3.0.0
info:
  title: Habit Tracker API
  version: 1.0.0
  description: API documentation for the Habit Tracker

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /api/habits:
    get:
      summary: Get all habits
      responses:
        '200':
          description: A list of habits
    post:
      summary: Create a new habit
      responses:
        '201':
          description: Habit created
  /api/habits/{id}:
    get:
      summary: Get a habit by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Habit found